### ISSUE TITLE
Requête url 

### ISSUE THREAD

**Issue by Hydci** [etalab/calendrier.api.gouv.fr#22]
Bonjour, 

Dans cette api y aurait-il une possibilité d'avoir une demande url mais avec la date d'aujourd'hui exemple
https://calendrier.api.gouv.fr/jours-feries/{zone}/{today}.json et d'avoir la réponse du férié en cour si il y a, ou bien false si aujourd'hui n'est pas un férié ?

**Comment by FabienBounoir** [comment]
Tu as juste a check dans le json si la clé "YYYY-MM-DD" existe dans le retour.
